#!/usr/bin/env python3

import os
import subprocess
import platform
import signal

def handle_linux_event():
    import pyudev

    context = pyudev.Context()
    monitor = pyudev.Monitor.from_netlink(context)
    monitor.filter_by(subsystem='block', device_type=None)

    for dev in iter(monitor.poll, None):
        # handle the insertion of the external storage device
        if dev.action == 'add':
            user = os.environ.get("SUDO_USER", None)

            hm_dir = os.path.expanduser(f"~{user}")    # home directory
            media_dir = hm_dir + "/.media/"     # media directory

            dev_name = dev.device_node
            label = subprocess.run(f'sudo lsblk {dev_name} -fsn -o UUID',
                                   shell=True, text=True,
                                   stdout=subprocess.PIPE,
                                   stderr=subprocess.PIPE)

            # ~/.media/<volume label>
            mnt_point = media_dir + label.stdout.strip()        # mount point

            subprocess.Popen(['mkdir', '-p', mnt_point])

            subprocess.run(f'sudo mount {dev_name} {mnt_point}', shell=True,
                           text=True, stdout=subprocess.PIPE,
                           stderr=subprocess.PIPE)
            device = subprocess.Popen([f'{mnt_point}/slauncher.py', dev_name], user=user)

        # handle the removal of the external storage device
        if dev.action == 'remove':
            # clean up
            device.send_signal(signal.SIGTERM)
            subprocess.run(f'sudo umount {dev_name}', shell=True, text=True,
                           stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            subprocess.Popen(['sudo', 'rmdir', f'{mnt_point}', f'{media_dir}/*'])

def handle_windows_event():
    import win32file
    import win32con

    if dbhInfo.Action == win32con.DBT_DEVICEARRIVAL:
        print("External storage device inserted:", dbhInfo.DeviceName)
        #dev = subprocess.Popen(['C:\\

system = platform.system()

if system == "Linux":
    handle_linux_event()

elif system == "Windows":
    handle_windows_event()

elif system == "Darwin":
    handle_darwin_event()
